---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(CodeClanData)
```


```{r}
#Question 1 ----
movies <- read_csv("data/movies.csv")
movies
```


```{r}
#Question 2 ----
movies_selected <- movies %>% 
  select(title, budget, runtime)

movies_selected
```


```{r}
#Question 3 ----
movies_selected %>% 
  summarise(na_title = sum(is.na(title)),
            na_budget = sum(is.na(budget)),
            na_runtime = sum(is.na(runtime)))

movies_selected
```



```{r}
#Question 4 ----
movies_runtime <- movies_selected %>% 
  mutate(runtime = na_if(runtime, "0"))

movies_runtime %>% 
    summarise(count = sum(is.na(runtime)))
```


```{r}
#Question 5 ----
movies_imputed <- movies_runtime %>% 
  mutate(runtime = coalesce(runtime, median(runtime), na.rm = TRUE))

movies_imputed %>% 
    summarise(count = sum(is.na(runtime)))
```


```{r}
#Question 6 ----
movies_imputed %>% 
  slice_max(runtime, n = 10)

movies_imputed %>% 
    slice_min(runtime, n = 10)
```


```{r}
#Question 7 ----
movies_imputed <- movies_imputed %>% 
  mutate(budget = if_else(budget < 100, 
                          median(budget), 
                          budget))
movies_imputed
```


```{r}
#Extension Q1 ----
movie_budgets <- movies_selected %>% 
  mutate(budget_type = case_when(
    budget < 12e6 ~ "Small Budget",
    budget < 40e6 ~ "Medium Budget",
    budget > 40e6 ~ "Big Budget"
  ))

movie_budgets
```

```{r}
#Extension Q2 ----
movies %>% 
  summarise(across(where(is.character), ~sum(is.na(.x))))

movies %>% 
  summarise(across(where(is.numeric), ~sum(is.na(.x))))
```

