---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
library(CodeClanData)
```
QUESTION 1

```{r}
drinks_content
```

```{r}
dim(drinks_content)
```

```{r}
glimpse(drinks_content)
```

QUESTION 2
```{r}
drinks_content %>%
  drop_na(Calories) %>% 
  select(Beverage_category, Beverage, Beverage_prep, Calories)
```

QUESTION 3
```{r}
drinks_content %>%
  drop_na(Calories) %>% 
  select(Beverage_category, Beverage, Beverage_prep, Calories) %>% 
  mutate(calorie_diff = Calories - 135)
```

QUESTION 4
```{r}
drinks_content %>%
  drop_na(Calories) %>% 
  select(Beverage_category, Beverage, Beverage_prep, Calories) %>% 
  mutate(calorie_diff = Calories - 135) %>% 
  group_by(Beverage_category) %>% 
  summarise(avg_cals = mean(Calories)) %>% 
  arrange(avg_cals)
```

QUESTION 5
```{r}
drinks_content %>%
  drop_na(Calories) %>% 
  select(Beverage_category, Beverage, Beverage_prep, Calories) %>% 
  mutate(calorie_diff = Calories - 135) %>% 
  group_by(Beverage_prep) %>% 
  summarise(avg_cals = mean(Calories)) %>% 
  arrange(desc(avg_cals))
```
QUESTION 6
```{r}
drinks_content %>% 
  drop_na(Calories) %>% 
  summarise(mean(Calories))
```

```{r}
drinks_content %>% 
  drop_na(Calories) %>%
  group_by(Beverage_prep) %>% 
  filter(Calories > 193.8719) %>% 
  summarise(count = n())
```

QUESTION 7
```{r}
drinks_content %>%
  drop_na(Calories) %>% 
  select(Beverage_category, Beverage, Beverage_prep, Calories) %>% 
  mutate(calorie_diff = Calories - 135) %>% 
  group_by(Beverage_category) %>% 
  mutate(avg_cals_cat = mean(Calories)) %>% 
  group_by(Beverage_prep) %>% 
  mutate(avg_cals_prep = mean(Calories)) %>%
  group_by(Beverage) %>% 
  mutate(avg_cals_bev = mean(Calories)) %>% 
  arrange(avg_cals_bev, avg_cals_cat, avg_cals_prep)
```

Question 7 Solution
```{r}
drinks_content %>%
  group_by(Beverage_category, Beverage, Beverage_prep) %>%
  summarise(min_calories = min(Calories)) %>%
  arrange(min_calories) %>% 
  head(5)
```
Question 7 Solution Continued
```{r}
drinks_content %>%
  filter(Beverage_category != "Tazo® Tea Drinks") %>% 
  group_by(Beverage_category, Beverage, Beverage_prep) %>%
  summarise(min_calories = min(Calories)) %>%
  arrange(min_calories) %>% 
  head(5)
```

