---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(CodeClanData)
library(fmsb)
```

```{r}
whisky <- CodeClanData::whisky %>% clean_names()
```

```{r}
whisky %>% 
  distinct(distillery)

whisky %>% 
  distinct(region)

whisky %>% 
  distinct(owner)

whisky %>% 
  distinct(floral)
```


```{r}
whisky <- whisky %>% 
  mutate(across(body:floral, as.numeric))
```



```{r}
whisky <- whisky %>% 
  pivot_longer(cols = body:floral,
               names_to = "notes",
               values_to = "score")
```



```{r}
whisky %>%
  filter(distillery == "Aberfeldy") %>% 
  ggplot(aes(x = notes,
             y = score,
             fill = region)) +
  geom_col() +
  scale_y_continuous(expand = c(0, 0)) +
  scale_y_continuous(limits = c(0, 4)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size = 14),
        axis.text.y = element_text(size = 14),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 14)) +
  labs(x = "Notes",
       y = "\nScore",
       fill = "Whisky Region")
```


```{r}
all_regions <- unique(whisky$region)

all_distilleries <- unique(whisky$distillery)
```





```{r}
whisky %>%
  group_by(owner) %>% 
  mutate(count = n()/12) %>% 
  ungroup() %>% 
  filter(count > 1) %>%
  filter(year_found == 1810) %>% 
  ggplot(aes(x = year_found,
             y = capacity,
             colour = owner)) +
  geom_point(aes(shape = region)) +
        theme(axis.text.x = element_text(size = 8),
            axis.text.y = element_text(size = 8),
            axis.title.x = element_text(size = 8),
            axis.title.y = element_text(size = 8),
            legend.title = element_text(size = 8),
            legend.text = element_text(size = 8),
            plot.title = element_text(size = 8)) +
  scale_y_continuous(labels = scales::comma) +
      labs(x = "Year Founded",
           y = "Capacity",
           colour = "Distillery Owner",
           title = "Distillery Capacity by Year Founed\n")
```

```{r}
whisky %>% 
  group_by(year_found) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))
```

