---
title: "Data Analyst Hospital & Health Care"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(lubridate)
```


```{r}
incidence <- read_csv("data/incidence_by_hb.csv") %>% clean_names()

hb <- read_csv("data/hb_geography_code.csv") %>% clean_names()
```


```{r}
incidence <- incidence %>% 
  left_join(select(hb, hb_name, hb), by = c("hb" = "hb"), keep = FALSE)
```


```{r}
nhs_borders <- incidence %>% 
  filter(hb_name == "NHS Borders")
```


```{r}
nhs_borders %>%
  filter(cancer_site == "All cancer types",
         sex == "All") %>% 
  ggplot(aes(x = year,
             y = incidences_all_ages))+
  geom_point()+
  geom_line(group = 1)+
  geom_smooth()
```
```{r}
nhs_borders %>% 
  distinct(cancer_site) %>% 
  arrange(cancer_site)
```


```{r}
nhs_borders_select <- nhs_borders %>% 
  filter(cancer_site %in% c("Breast", "Carcinoma in situ of the breast", "Colon", "Colorectal cancer", "Mesothelioma", "Prostate", "Rectum and rectosigmoid junction", "Trachea, bronchus and lung")) %>% 
  mutate(cancer_common = case_when(
    str_detect(cancer_site, "Breast") ~ "Breast",
    str_detect(cancer_site, "Carcinoma in situ of the breast") ~ "Breast",
    str_detect(cancer_site, "Colon") ~ "Bowel",
    str_detect(cancer_site, "Colorectal cancer") ~ "Bowel",
    str_detect(cancer_site, "Rectum and rectosigmoid junction") ~ "Bowel",
    str_detect(cancer_site, "Prostate") ~ "Prostate",
    str_detect(cancer_site, "Mesothelioma") ~ "Lung",
    str_detect(cancer_site, "Trachea, bronchus and lung") ~ "Lung"
  ), .after = cancer_site)
```


```{r}
nhs_borders_select %>%
  filter(cancer_common == "Breast",
         sex == "All") %>%
  group_by(year) %>% 
  summarise(total_incidences_breast = sum(incidences_all_ages)) %>% 
  ggplot(aes(x = year,
             y = total_incidences_breast))+
  geom_point()+
  geom_line()+
  geom_smooth()
```


```{r}
nhs_borders_select %>%
  filter(cancer_common == "Bowel",
         sex == "All") %>%
  group_by(year) %>% 
  summarise(total_incidences_bowel = sum(incidences_all_ages)) %>% 
  ggplot(aes(x = year,
             y = total_incidences_bowel))+
  geom_point()+
  geom_line()+
  geom_smooth()
```


```{r}
nhs_borders_select %>%
  filter(cancer_common == "Lung",
         sex == "All") %>%
  group_by(year) %>% 
  summarise(total_incidences_lung = sum(incidences_all_ages)) %>% 
  ggplot(aes(x = year,
             y = total_incidences_lung))+
  geom_point()+
  geom_line()+
  geom_smooth()
```


```{r}
nhs_borders_select %>%
  filter(cancer_common == "Prostate",
         sex == "Male") %>%
  group_by(year) %>% 
  summarise(total_incidences_prostate = sum(incidences_all_ages)) %>% 
  ggplot(aes(x = year,
             y = total_incidences_prostate))+
  geom_point()+
  geom_line()+
  geom_smooth()
```


```{r}
nhs_borders_prostate_recode <- nhs_borders_select %>%
  filter(cancer_common == "Prostate") %>% 
  mutate(sex = recode(sex,
                      "Male" = "All"))
```


```{r}
nhs_borders_select <- nhs_borders_select %>% 
  filter(cancer_common != "Prostate")
```


```{r}
nhs_borders_select <- nhs_borders_select %>% 
  bind_rows(nhs_borders_prostate_recode)
```


```{r}
nhs_borders_select %>% 
  filter(sex == "All") %>% 
  group_by(year) %>% 
  summarise(total_incidies = sum(incidences_all_ages)) %>% 
  ggplot(aes(x = year,
             y = total_incidies))+
  geom_point()+
  geom_line(group = 1)+
  geom_smooth()
```


```{r}
nhs_borders_select %>% 
  filter(sex == "All") %>% 
  group_by(year) %>% 
  summarise(total_incidies = sum(incidences_all_ages)) %>% 
  ggplot(aes(x = year,
             y = total_incidies))+
  geom_col()+
  geom_smooth()
```


```{r}
nhs_borders_select %>% 
  filter(sex == "All") %>% 
  group_by(year, cancer_common) %>% 
  summarise(total_indicies = sum(incidences_all_ages)) %>% 
  ggplot(aes(x = year,
             y = total_indicies)) +
  geom_point()+
  geom_line(aes(group = cancer_common, colour = cancer_common))
```


```{r}
nhs_borders_select %>% 
  filter(sex == "All") %>% 
  group_by(year, cancer_common) %>% 
  summarise(total_indicies = sum(incidences_all_ages)) %>% 
  ggplot(aes(x = year,
             y = total_indicies)) +
  geom_col(aes(fill = cancer_common), position = "stack")+
  coord_flip()
```

