---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(modelr)
library(readxl)
library(GGally)
library(pROC)
```

```{r}
juice <- read_csv("data/orange_juice.csv") %>% clean_names()
```


```{r}
head(juice)
```


```{r}
library(skimr)

skim(juice)
```

## Data wrangling 
```{r}
juice <- juice %>% 
  mutate(purchase_mm = if_else(purchase == "MM", TRUE, FALSE)) %>% # change to logical
  mutate(quarter = case_when(
    weekof_purchase <= 239 ~ "Q1", # deal with weekof_purchase column
    weekof_purchase <= 252 ~ "Q2",
    weekof_purchase <= 265 ~ "Q3",
    weekof_purchase <= 278 ~ "Q4"
  )) %>% 
  mutate(across(where(is_character), as_factor)) %>% # change characters to factors
  select(-c(purchase, weekof_purchase, store_id)) # drop columns not required
```


```{r}
juice <- juice %>% 
  select(-c(price_diff, list_price_diff, sale_price_mm, sale_price_ch)) # drop more columns due to aliases

alias(purchase_mm ~ .,
      data = juice)
```


```{r}
juice %>% skim()
```

## split data for ggpairs plot
```{r}
split1 <- juice %>% 
  select(price_ch:special_ch, purchase_mm) %>% 
  select(purchase_mm, everything())

split2 <- juice %>% 
  select(special_mm:store, purchase_mm) %>% 
  select(purchase_mm, everything())

split3 <- juice %>% 
  select(purchase_mm, quarter)
```


```{r}
split1 %>% 
  ggpairs()

split2 %>% 
  ggpairs()

split3 %>% 
  ggpairs()
```


## split into train / test
```{r}
n_data <- nrow(juice)

test_index <- sample(1:n_data, size = 0.2 * n_data)

juice_test <- slice(juice, test_index)

juice_train <- slice(juice, -test_index)
```


```{r}
library(glmulti)
```


```{r}
glmulti_search_all_mains <- glmulti(
  purchase_mm ~ .,
  data = juice_train,
  level = 1,
  method = "h",
  crit = "bic",
  confsetsize = 10,
  plotty = FALSE,
  report = TRUE,
  fitfunction = "glm",
  family = binomial(link = "logit")
)
```


```{r}
summary(glmulti_search_all_mains)
```


```{r}
mod_glm <- glm(purchase_mm ~ store7 + price_mm + disc_mm + loyal_ch,
               data = juice_train,
               family = binomial(link = "logit"))

summary(mod_glm)
```


```{r}
glmulti_search_previous_mains_one_pair <- glmulti(
  purchase_mm ~ store7 + price_mm + disc_mm + loyal_ch,
  data = juice_train,
  level = 2,
  method = "h",
  crit = "bic",
  confsetsize = 10,
  marginality = TRUE,
  minsize = 5,
  maxsize = 6,
  plotty = FALSE,
  report = TRUE,
  fitfunction = "glm",
  family = binomial(link = "logit")
)

summary(glmulti_search_previous_mains_one_pair)
```



```{r}
top <- weightable(glmulti_search_previous_mains_one_pair)


```



AUC for test data
 
