---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
```

```{r}
#Quesiton 1 ----
card <- read_csv("data/CardBase.csv")
customer <- read_csv("data/CustomerBase.csv")
fraud <- read_csv("data/FraudBase.csv")
transaction <- read_csv("data/TransactionBase.csv")
```

```{r}
card
customer
fraud
transaction
```

```{r}
#Question 2 ----
card %>% 
  left_join(customer, by = "Cust_ID")
```

```{r}
#Question 3 ----
fraud %>% 
  full_join(transaction, by = "Transaction_ID")
```

```{r}
#Question 4 ----
cards_with_transactions <- card %>%
  semi_join(transaction, by = c("Card_Number" = "Credit_Card_ID"))

```

```{r}
#Question 5 ----
hats <- read_csv("data/hat_observations.csv")
hats
```


```{r}
#Question 5 cont ----

hats_separate <- hats %>% 
  separate(col = observation,
           into = c("hat_colour", "hat_type"),
           sep = ",")
```

```{r}
#Question 6 ----

hats_separate %>% 
  unite(date, c("day", "month", "year"), sep = ":") %>%
  filter(hat_type == "beret") %>% 
  group_by(date) %>% 
  summarise(total = sum(observation_count)) %>% 
  slice_max(total)
```

```{r}
#Extension Q1 ----

# join_1 <- card %>% 
#   inner_join(customer, by = "Cust_ID")
# 
# join_2 <- join_1 %>% 
#   inner_join(transaction, by = c("Card_Number" = "Credit_Card_ID"))
# 
# join_3 <- join_2 %>% 
#   inner_join(fraud, by = "Transaction_ID")

#Above but using %>% to make it slicker ----

join_card <- card %>% 
  inner_join(customer, by = "Cust_ID") %>% 
  inner_join(transaction, by = c("Card_Number" = "Credit_Card_ID")) %>% 
  inner_join(fraud, by = "Transaction_ID")
```


```{r}
#Extension Q2 ----

exams <- read_csv("data/exam_scores.csv")
view(exams)
```

```{r}
exams_longer <- exams %>% 
  pivot_longer(cols = starts_with("exam"),
               names_to = "exam_question",
               values_to = "score",
               names_prefix = "exam_")

view(exams_longer)
```

