---
title: "R Notebook"
output: html_notebook
---

```{r}
#Question 1 ----
weather <- list(Thursday = list(temp = 21, chance_of_rain = 5, wind_speed = 10),
                Friday = list(temp = 20, chance_of_rain = 60, wind_speed = 6),
                Saturday = list(temp = 19, chance_of_rain = 10, wind_speed = 22))
```

```{r}
#Question 2 ----

#i. ----
weather[["Thursday"]][["chance_of_rain"]]

#ii. ----
weather[["Saturday"]][["wind_speed"]]

#iii. ----
weather[["Thursday"]][["temp"]]
```

```{r}
#Question 3 ----
days_of_week <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")
weeks <- c("week_1", "week_2")

temperatures <- matrix(c(20, 17, 19, 20, 18, 16, 16, 18, 19, 17, 16, 17, 16, 16), nrow = 2, byrow = TRUE)

colnames(temperatures) <- paste(days_of_week)
rownames(temperatures) <- paste(weeks)

temperatures
```

```{r}
#Question 4 ----

#i. ----
temperatures["week_2", "Wednesday"]

#ii. ----
temperatures["week_2", ]

#iii. ----
temperatures[ , c("Monday", "Wednesday", "Friday")]
```


```{r}
#Question 5 ----

format_chars_nums <- function(x) {
  if (is.character(x)) {
    ans <- paste("The answer is:", x)
  }
  if (is.numeric(x)) {
    if (x < 10) {
      ans <- paste(x)
    } else {
      ans <- paste(x / 10)
    }
  }
  ans
}

format_chars_nums("hello") 
```

```{r}
#Question 6 ----
animals_1 <- c("dog", "cat", "lion")
animals_2 <- c("lion", "zeebra", "dog")


vector_checker <- function(x, y) {
  if(all(x == y)) {
    paste(print("Exactly the same"))
  } else {
    if(all(sort(x) == sort(y))) {
      paste(print("The same"))
    } else {
      paste(print("Different"))
    }
  }
}

vector_checker(animals_2, animals_1)
```


```{r}
#Question 7 ----

multi_matrix <- matrix(NA, nrow = 12, ncol = 12)
num_row <- dim(multi_matrix)[1]
num_col <- dim(multi_matrix)[2]

for (row_i in 1:num_row) {
  for (col_i in 1:num_col) {
    multi_matrix[row_i, col_i] <- row_i * col_i
  }
}

multi_matrix
```

cat(... , file = "", sep = " ", fill = FALSE, labels = NULL,

```{r}
#Question 8 ----

example_vector <- c(1, 2, 3, 4, 5, 1, 3, 4, 5, 1, 3, 4, 4, 3, 3, 3, 3)
example_vector_length = length(example_vector)

art_histogram <- function(x) {
  
  distinct <- sort(unique(x))          #This sorts x into unique values
                                       
  for (i in distinct) {
    
    count <- sum(x == i)               #This creates a variable to count the number of                                         unique values
    cat(i)                             #This
    cat(" | ")
    cat(rep("*", count))               #This prints * for how many counts
    cat("\n")
  }
}
art_histogram(example_vector)
```



```{r}
x <- 1:3
y <- 3:1
z <- 1:3

x == y
x == z

identical(x, y)
identical(x, z)

all(x == y)
all(x == z)

any(x == y)
any(x == z)
```

